apiVersion: v1
kind: Service
metadata:
  name: strengthservice  
spec:
  selector:
    app: strengthservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 18605
      targetPort: 18605
      nodePort: 30001